"""Fit PulsejetCorrectionCoefficients against a calibration dataset.

No scipy in this environment -- implements Hooke-Jeeves pattern search
(coordinate-wise step-and-shrink), a standard derivative-free method,
adequate for 4 bounded parameters. Holds out every 4th calibration point for
validation, never used in fitting.
"""

from __future__ import annotations

import csv
import json
from dataclasses import replace
from pathlib import Path

from douglas_dart.config import load_reference_case
from douglas_dart.pulsejet_closed_form import PulsejetCorrectionCoefficients, evaluate_pulsejet_closed_form

IN_PATH = Path("results/generated/pulsejet_calibration/mach_sweep_reference_case.csv")
OUT_PATH = Path("configs/pulsejet_closed_form_calibration.yaml")

CASE = load_reference_case("configs/reference_case.yaml")

with IN_PATH.open() as f:
    all_rows = list(csv.DictReader(f))
for row in all_rows:
    row["mach"] = float(row["mach"])
    row["altitude_m"] = float(row["altitude_m"])
    row["net_thrust_n"] = float(row["net_thrust_n"])
    row["fuel_mass_flow_kg_per_s"] = float(row["fuel_mass_flow_kg_per_s"])

train_rows = [r for i, r in enumerate(all_rows) if i % 4 != 0]
holdout_rows = [r for i, r in enumerate(all_rows) if i % 4 == 0]
print(f"{len(train_rows)} training points, {len(holdout_rows)} holdout points")

PARAM_NAMES = ("tail_impulse_fraction", "tail_time_fraction", "fresh_air_inflow_discount", "net_thrust_efficiency")
BOUNDS = {
    "tail_impulse_fraction": (-0.95, 10.0),
    "tail_time_fraction": (-0.95, 10.0),
    "fresh_air_inflow_discount": (1e-4, 5.0),
    "net_thrust_efficiency": (0.05, 10.0),
}


def _make_coefficients(values: dict[str, float]) -> PulsejetCorrectionCoefficients:
    return PulsejetCorrectionCoefficients(
        tail_impulse_fraction=values["tail_impulse_fraction"],
        tail_time_fraction=values["tail_time_fraction"],
        fresh_air_inflow_discount=values["fresh_air_inflow_discount"],
        net_thrust_efficiency=values["net_thrust_efficiency"],
        calibrated=True,
        source="scripts/pulsejet_calibration_fit.py, Mach-only sweep, reference_case.yaml geometry",
    )


def _sum_squared_error(values: dict[str, float], rows: list[dict]) -> float:
    coefficients = _make_coefficients(values)
    total = 0.0
    for row in rows:
        result = evaluate_pulsejet_closed_form(
            CASE.pulsejet, CASE.selector, CASE.nozzle, CASE.fuel, row["altitude_m"], row["mach"], coefficients
        )
        total += (result.mean_net_thrust_n - row["net_thrust_n"]) ** 2
    return total


def _clip(name: str, value: float) -> float:
    lo, hi = BOUNDS[name]
    return min(max(value, lo), hi)


def hooke_jeeves(initial: dict[str, float], rows: list[dict], iterations: int = 60) -> dict[str, float]:
    current = dict(initial)
    step = {name: max(abs(current[name]) * 0.5, 0.05) for name in PARAM_NAMES}
    best_cost = _sum_squared_error(current, rows)
    print(f"start cost={best_cost:.2f}  {current}")

    for iteration in range(iterations):
        improved = False
        for name in PARAM_NAMES:
            for direction in (1.0, -1.0):
                trial = dict(current)
                trial[name] = _clip(name, trial[name] + direction * step[name])
                cost = _sum_squared_error(trial, rows)
                if cost < best_cost:
                    current = trial
                    best_cost = cost
                    improved = True
        if not improved:
            for name in PARAM_NAMES:
                step[name] *= 0.5
        if all(s < 1e-5 for s in step.values()):
            break
        if iteration % 10 == 0:
            print(f"iter={iteration:3d} cost={best_cost:.2f}  {current}")

    print(f"final cost={best_cost:.2f}  {current}")
    return current


initial_guess = {
    "tail_impulse_fraction": 0.0,
    "tail_time_fraction": 0.0,
    "fresh_air_inflow_discount": 0.02,
    "net_thrust_efficiency": 1.0,
}
fitted = hooke_jeeves(initial_guess, train_rows)

train_rmse_n = (_sum_squared_error(fitted, train_rows) / len(train_rows)) ** 0.5
holdout_rmse_n = (_sum_squared_error(fitted, holdout_rows) / len(holdout_rows)) ** 0.5
print(f"\ntrain RMSE: {train_rmse_n:.2f} N   holdout RMSE: {holdout_rmse_n:.2f} N")

coefficients = _make_coefficients(fitted)
OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
with OUT_PATH.open("w") as f:
    f.write("# Generated by scripts/pulsejet_calibration_fit.py -- do not hand-edit.\n")
    f.write(f"# Mach-only calibration at reference_case.yaml geometry (chamber_volume_m3,\n")
    f.write(f"# throat_diameter_m, exit_to_throat_area_ratio held fixed). Full multi-\n")
    f.write(f"# dimensional DOE across those geometry variables is a later phase.\n")
    f.write(f"# train RMSE: {train_rmse_n:.3f} N, holdout RMSE: {holdout_rmse_n:.3f} N\n")
    f.write("tail_impulse_fraction: " + repr(fitted["tail_impulse_fraction"]) + "\n")
    f.write("tail_time_fraction: " + repr(fitted["tail_time_fraction"]) + "\n")
    f.write("fresh_air_inflow_discount: " + repr(fitted["fresh_air_inflow_discount"]) + "\n")
    f.write("net_thrust_efficiency: " + repr(fitted["net_thrust_efficiency"]) + "\n")
    f.write("calibrated: true\n")
print(f"Wrote {OUT_PATH.resolve()}")
