"""V4 report: re-fly the selected design and emit the tables.

Plotting lives in scripts/simple_model_v4_plots.py, which reuses run_demo's
own flight-profile and propulsion figures so V4 is presented in the same
layout as V2/V3 rather than a second, divergent plotting stack.

Usage: .venv/Scripts/python scripts/simple_model_v4_report.py
Writes out_simple_model/v4_optimal_design.md (+ the three PNGs it embeds)
"""
from __future__ import annotations

import json
import sys
from math import degrees
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from scripts.simple_model_v4_baseline import (  # noqa: E402
    V4_WING, fly, mass_block, v4_geometry)
from scripts.simple_model_v4_plots import main as regenerate_plots  # noqa: E402
from simple_model.constants import CD0_FRONTAL  # noqa: E402
from simple_model.flight_sim import (  # noqa: E402
    V3_FLOOR_ALTITUDE_M, V4_SPIRAL_BANK_DEG)

OUT = ROOT / "out_simple_model"
POWERED = ["v3_climb", "v4_pushover", "v3_dive", "v4_pullout", "drag_strip"]
PHASE_LABELS = {
    "v3_climb": "spiral climb", "v4_pushover": "pushover arc",
    "v3_dive": "dive", "v4_pullout": "pull-out arc", "drag_strip": "drag strip",
}


def phase_table(r) -> str:
    rows = []
    for phase in POWERED:
        pts = [s for s in r.states if s.mode == phase]
        if not pts:
            continue
        rows.append(
            f"| {PHASE_LABELS[phase]} | {pts[0].time_s:.1f} – {pts[-1].time_s:.1f} "
            f"| {pts[0].altitude_m:.0f} → {pts[-1].altitude_m:.0f} "
            f"| {pts[0].mach:.3f} → {pts[-1].mach:.3f} "
            f"| {degrees(pts[0].flight_path_angle_rad):+.1f} → "
            f"{degrees(pts[-1].flight_path_angle_rad):+.1f} "
            f"| {max(s.load_n_total for s in pts):.2f} |")
    return "\n".join(rows)


def gate_cost_table(robust: dict) -> str:
    best: dict[float, dict] = {}
    for row in sorted(robust["ranked"],
                      key=lambda r: (-r["thrust_loss_tolerated_pct"],
                                     -r["nominal"]["payload_margin_kg"])):
        best.setdefault(row["gate"], row)
    lines = []
    for g in sorted(best):
        row = best[g]
        n = row["nominal"]
        mark = "**" if g >= 0.50 else ""
        lines.append(
            f"| {mark}{g:.2f}{mark} | {row['thrust_loss_tolerated_pct']:.1f} | "
            f"{n['payload_margin_kg']:.3f} | {n['peak_tw']:.2f} | "
            f"{n['peak_n_total']:.2f} | {n['traverse_g']:.3f} | {row['top_m']:.0f} |")
    return "\n".join(lines)


def main() -> None:
    OUT.mkdir(exist_ok=True)
    robust = json.loads((OUT / "v4_robust.json").read_text())
    pick = json.loads((OUT / "v4_pick.json").read_text())
    gate, top, dive, climb, n = (pick["gate"], pick["top_m"], pick["dive_deg"],
                                 pick["climb_deg"], pick["pullout_n"])
    r = fly(climb_deg=climb, dive_deg=dive, floor_m=V3_FLOOR_ALTITUDE_M,
            gate_mach=gate, pullout_n=n, top_altitude_m=top)
    geom = v4_geometry()
    mass = mass_block(r, geom, V4_WING)
    regenerate_plots()

    entry = next((row for row in robust["ranked"]
                  if (row["gate"], row["top_m"], row["dive_deg"],
                      row["climb_deg"], row["pullout_n"]) == tuple(
                          [gate, top, dive, climb, n])), None)
    tolerated = entry["thrust_loss_tolerated_pct"] if entry else float("nan")

    body_length = (geom.chamber_length_m + geom.throat_length_m
                   + 3.0 * geom.diameter_m)
    md = f"""# V4 optimal design — ramjet lights in the dive

Generated by `scripts/simple_model_v4_report.py`. Closed-form `simple_model`,
CD0_FRONTAL = {CD0_FRONTAL}. **V2 and V3 remain frozen and untouched**
(`docs/v2_frozen/`, `docs/v3_frozen/`, re-verified bit-identical).

## The design

| item | value |
|---|---|
| body = chamber diameter | {geom.diameter_m*1000:.1f} mm |
| throat diameter | {geom.throat_diameter_m*1000:.1f} mm (area fraction {(geom.throat_diameter_m/geom.diameter_m)**2:.4f}) |
| chamber length | {geom.chamber_length_m*1000:.1f} mm |
| duct (cone + tailpipe) | {geom.throat_length_m*1000:.1f} mm |
| body length (nose+tail incl.) | {body_length*1000:.0f} mm |
| wing | span {V4_WING.span_m*1000:.0f} mm, AR {V4_WING.aspect_ratio:.3f}, taper {V4_WING.taper_ratio:.3f}, sweep {V4_WING.sweep_deg:.2f}°, {V4_WING.airfoil.display_name} |
| fuel | {geom.fuel.display_name} |

## The trajectory

| item | value |
|---|---|
| **ramjet gate** | **M {gate:.2f}, must be crossed while descending** |
| top of climb | {top:.0f} m (commanded) |
| climb | {climb:.0f}° **spiral**, {V4_SPIRAL_BANK_DEG:.0f}° bank, ground-track R = {r.spiral_radius_m:,.0f} m |
| pushover (pitch-down) arc | R = **{r.pushover_radius_m:,.0f} m**, {r.pushover_duration_s:.1f} s, {r.states[0].load_n_yaw:.2f}→0 g commanded |
| dive | {dive:.0f}° |
| pull-out (pitch-up) arc | R = **{r.pullout_radius_m:,.0f} m**, {r.pullout_duration_s:.1f} s, {n:.1f} g nominal |
| floor | {V3_FLOOR_ALTITUDE_M:.1f} m, flown minimum {r.min_powered_altitude_m:.1f} m |
| drag strip | 1.0° to cutoff |

## Mission result

| metric | value |
|---|---|
| ramjet lightoff | **M {r.ramjet_lightoff_mach:.3f} at {r.ramjet_lightoff_altitude_m:.0f} m, t {r.ramjet_lightoff_time_s:.1f} s, in `{r.ramjet_lightoff_mode}`** |
| lit in the dive | **{r.ramjet_lit_in_dive}** |
| dive exit Mach | {r.dive_exit_mach:.3f} — this is the `dive_end_mach` cap, **not** spare reachability (see below) |
| peak Mach | {max(s.mach for s in r.states):.3f} |
| motor cutoff reached | {r.motor_cutoff_reached} |
| peak T/W | {max(s.thrust_to_weight for s in r.states):.2f} |
| min traverse acceleration | {r.min_traverse_accel_g:.3f} g @ M {r.min_traverse_accel_mach:.2f} — **below the 0.25 g gate** |
| min powered acceleration | {r.min_powered_accel_g:+.4f} g @ M {r.min_accel_mach:.3f} — **negative, at the top of climb** |
| min thrust margin (engine-only) | {r.min_powered_thrust_margin:.3f} — **below the 1.15 gate** |
| **peak body load (total)** | **{r.peak_load_n_total:.2f} g** in `{r.peak_load_mode}` |
| peak yaw-axis (normal) load | {r.peak_load_n_yaw:.2f} g |
| peak roll-axis (axial) load | {r.peak_load_n_roll:.2f} g |
| fuel burned / tank capacity | {mass['fuel_burned_kg']:.3f} / {mass['tank_capacity_kg']:.3f} kg |
| dry mass (re-derived) | {mass['dry_mass_kg']:.3f} kg |
| **payload margin** | **{mass['payload_margin_kg']:.3f} kg** |
| stall speed at landing | {r.states[-1].stall_speed_m_per_s:.1f} m/s (cap 45) |
| safe landing | {r.safe_landing} |
| **pulsejet thrust loss tolerated** | **−{tolerated:.1f} %** and still lights in the dive |

## Phases

| phase | t (s) | altitude (m) | Mach | γ (deg) | peak load (g) |
|---|---|---|---|---|---|
{phase_table(r)}

## What the M 0.50 gate costs

Most-robust design at each gate on the *same airframe*. "−thrust %" is how
much pulsejet thrust the design can lose and still light in the dive — the
only margin that means anything for a gate this close to the vehicle's
ceiling.

| gate | −thrust % tolerated | payload (kg) | peak T/W | peak load (g) | traverse (g) | top (m) |
|---|---|---|---|---|---|---|
{gate_cost_table(robust)}

Gates below 0.50 are **context only** — they are flown to price the directive,
not to propose a lower gate.

Note the 0.50 row is the *highest-payload* design at that robustness level
(dive 16°); the **frozen** design is dive 14°, which gives up 0.05 kg of
payload to carry 0.5 g less body load. Reading across, the directive costs
roughly **0.4 kg of payload, 0.06 of traverse acceleration, and 300 m of extra
top-of-climb** versus a 0.48 gate — and 300 m of top is the expensive part,
because it spends the margin against the pulsejet's altitude ceiling.

## Reachability ceiling

Pulsejet-only dive-exit Mach (ramjet gate set unreachable, so the dive runs on
the pulsejet alone). A gate above this can never fire in the dive:

| | value |
|---|---|
| absolute best measured | **M 0.533** (top 1200 m, dive 18°, 5 g pull-out) |
| at this design's top/dive | ~M 0.52 |
| **so M 0.55+ is unreachable** | at any top under the FP pulsejet ceiling |

A steeper dive makes this **worse**, not better, at a fixed top: at top 1000 m
and 3 g, dive 10° gives M 0.516 and dive 30° gives M 0.500. The dive is
drag-limited, so shortening the path costs more than the extra gravity buys.
Top of climb is the only lever that moves it (600 m → 1200 m: 0.482 → 0.523),
and that lever runs into the FP flame-out ceiling.

## Why the climb is a spiral

Same top (1100 m), same everything else:

| climb | min powered accel (g) | top-of-climb M | downrange at cutoff | lands safely? | payload (kg) |
|---|---|---|---|---|---|
| straight 6° | −0.0213 | 0.387 | 17.53 km | **no** | 4.749 |
| spiral 6° | −0.0213 | 0.381 | **7.10 km** | **yes** | 4.679 |
| straight 8° | −0.0193 | 0.362 | 15.14 km | **no** | 4.947 |
| spiral 8° | −0.0178 | 0.352 | **7.36 km** | **yes** | 4.850 |

The spiral costs **0.07 kg of payload and 0.006 Mach** and buys back 10.4 km of
downrange — which is the difference between landing at the launch point and
landing 4–6 km short of it. Bank load (1.155 g) and its induced drag are
charged; roll-in/roll-out and heading alignment at the top are not modelled.

## Body load is tunable with `dive_end_mach` — the cheapest knob here

The dive on this design terminates on `dive_end_mach`, **not** on the floor, so
that constant decides how fast the vehicle is when the pull-out starts — and
speed is what sets the arc load. Every row below still lights in the dive and
still survives −10 % thrust:

| `dive_end_mach` | peak load (g) | min altitude (m) | payload (kg) | peak T/W |
|---|---|---|---|---|
| 0.52 | 3.01 | 332 | 4.562 | 5.92 |
| 0.55 | 3.28 | 237 | 4.641 | 5.99 |
| 0.58 | 3.39 | 176 | 4.670 | 6.04 |
| **0.60 (frozen — V3's own value)** | **3.45** | **146** | **4.679** | **6.06** |
| 0.65 | 4.24 | 122 (on the floor) | 4.690 | 6.08 |

Frozen at 0.60 because it is V3's value and the brief was to stay close to V3,
and 3.45 g is inside the 4 g design limit. **If you want lower loads, 0.55
costs 0.04 kg of payload and buys 0.17 g less body load plus 90 m more floor
clearance** — a one-line change to `dive_end_mach` in
`docs/v4_frozen/design.json`. Above 0.65 the floor becomes binding and the
pull-out limiter starts pulling harder than the 3 g nominal to hold it.

## Gates NOT met — read this

| gate | target | V4 | note |
|---|---|---|---|
| min traverse acceleration | ≥ 0.25 g | **0.163 g** | direct cost of the 0.50 gate — 0.42 gives 0.415 g on this airframe |
| min powered acceleration | > 0 | **−0.021 g** | at the top of climb: the vehicle is *at* its climb ceiling at 1100 m. Negative at every top ≥ 800 m. |
| min powered thrust margin | ≥ 1.15 | **0.855** | engine-only margin at lightoff; never met by any V2/V3/V4 configuration |

The last two are the same engine-limited gates the V3 campaign never closed
across ~450 closed-form and ~40 FP flights. The learnings doc is explicit that
they are engine/drag problems, not trajectory problems, and V4 does not close
them either. The traverse figure *is* a V4 regression (frozen V3 scores
0.261 g) and it is the price of moving the gate from 0.45 to 0.50.

## Biggest risk

Top of climb 1100 m sits just under the FP pulsejet flame-out ceiling
(~1250 m alive / 1275 m dead at CONFIRM — **and that ceiling dropped ~200 m
when the grid was refined from 162 to 324 cells**). `simple_model` has no
flame-out model at all; it only lapses thrust as (ρ/ρ_SL)³. Independently,
this model already shows the climb going marginally negative in acceleration
at that altitude, which is the same wall the FP model found ("at 1100 m the
duct makes 83.5 N; an 8° climb needs ~81 N"). **This is the number to check
first in `medium_model`.**

## Alternative — more payload, one step less robust

`top 1100 m, dive 18°, climb 8° spiral, pull-out 2.0 g`, same M 0.50 gate:
payload **4.925 kg**, peak load **3.13 g**, T/W **6.03**, traverse **0.235 g**,
tolerates **−8 %** thrust. Better on all four stated criteria; chosen against
only because V3's headline failure was a design that passed at one fidelity
and failed at the next. Switch by editing `out_simple_model/v4_pick.json`.

## Plots

The established flight-profile layout: mode shading on every time panel,
ft/lb units, mode-coloured trajectory (the spiral climb is the vertical track
at downrange 0; the pushover and pull-out arcs are the orange and green
segments).

![flight profile](flight_profile_v4.png)

![propulsion](propulsion_v4.png)

Body loading and the pitch arcs, same visual language, framed on the powered
mission (the unpowered return half-loop pulls a fixed 6 g by construction and
would otherwise set the scale):

![body loading](body_loading_v4.png)
"""
    (OUT / "v4_optimal_design.md").write_text(md, encoding="utf-8")
    print(f"wrote {OUT/'v4_optimal_design.md'}")


if __name__ == "__main__":
    main()
